// This file is an augmentation to the built-in ImportMeta interface
// Thus cannot contain any top-level imports
// <https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation>

type ImportMetaEnv = {
    BASE_URL: string;
    MODE: string;
    DEV: boolean;
    PROD: boolean;
    SSR: boolean;
    // Auto-generated by `npx vite-envs update-types`
    HEADER_LOGO: string;
    HEADER_HIDE_ONYXIA: string;
    HEADER_TEXT_BOLD: string;
    HEADER_TEXT_FOCUS: string;
    PALETTE_OVERRIDE: string;
    FONT: string;
    SPLASHSCREEN_LOGO: string;
    SPLASHSCREEN_LOGO_SCALE_FACTOR: string;
    FAVICON: string;
    TAB_TITLE: string;
    SOCIAL_MEDIA_TITLE: string;
    SOCIAL_MEDIA_DESCRIPTION: string;
    SOCIAL_MEDIA_IMAGE: string;
    BACKGROUND_ASSET: string;
    HEADER_LINKS: string;
    LEFTBAR_LINKS: string;
    DISABLE_HOMEPAGE: string;
    HOMEPAGE_LOGO: string;
    HOMEPAGE_MAIN_ASSET: string;
    HOMEPAGE_MAIN_ASSET_X_OFFSET: string;
    HOMEPAGE_MAIN_ASSET_Y_OFFSET: string;
    HOMEPAGE_MAIN_ASSET_SCALE_FACTOR: string;
    HOMEPAGE_HERO_TEXT: string;
    HOMEPAGE_HERO_TEXT_AUTHENTICATED: string;
    HOMEPAGE_BELOW_HERO_TEXT: string;
    HOMEPAGE_BELOW_HERO_TEXT_AUTHENTICATED: string;
    HOMEPAGE_CALL_TO_ACTION_BUTTON: string;
    HOMEPAGE_CALL_TO_ACTION_BUTTON_AUTHENTICATED: string;
    HOMEPAGE_CARDS: string;
    TERMS_OF_SERVICES: string;
    CUSTOM_HTML_HEAD: string;
    GLOBAL_ALERT: string;
    ENABLED_LANGUAGES: string;
    DISABLE_COMMAND_BAR: string;
    DISABLE_PERSONAL_INFOS_INJECTION_IN_GROUP: string;
    DISABLE_AUTO_LAUNCH: string;
    SAMPLE_DATASET_URL: string;
    ONYXIA_VERSION: string;
    ONYXIA_VERSION_URL: string;
    ONYXIA_API_URL: string;
    CUSTOM_RESOURCES_URL: string;
    ALLOW_THEME_TESTING_VIA_URL: string;
};

interface ImportMeta {
    url: string;

    readonly hot?: import("./hot").ViteHotContext;

    readonly env: ImportMetaEnv;

    glob: import("./importGlob").ImportGlobFunction;
}
