import * as fs from "fs";
import { join as pathJoin } from "path";
import { assert, is } from "tsafe";

type Params = {
    distDirPath: string;
    mergedEnv: Record<string, unknown>;
    nameOfTheGlobal: string;
};

export function createSwEnvJsFile(params: Params) {
    const { distDirPath, mergedEnv, nameOfTheGlobal } = params;

    const envWithValuesInBase64 = Object.fromEntries(
        Object.entries(mergedEnv).map(([key, value]) => [
            key,
            Buffer.from(JSON.stringify(value), "utf8").toString("base64")
        ])
    );

    const swEnv = [
        `// NOTE: This file is auto-generated by vite-envs.`,
        `// It enables you to access environment variables in your service worker.`,
        `// To use it, use \`importScripts("swEnv.js")\` at the top of your worker file.`,
        `// (Assuming your worker file is next to this file)`,
        `// Then you can access your environment variables via \`self.${nameOfTheGlobal}.MY_VAR\``,
        ``,
        `const envWithValuesInBase64 = ${JSON.stringify(envWithValuesInBase64, null, 2)
            .replace(/^"/, "")
            .replace(/"$/, "")};`,
        `const env = {};`,
        `Object.keys(envWithValuesInBase64).forEach(function (name) {`,
        `    env[name] = JSON.parse(`,
        `      new TextDecoder().decode(`,
        `        Uint8Array.from(`,
        `          atob(envWithValuesInBase64[name]),`,
        `          c => c.charCodeAt(0)`,
        `        )`,
        `      )`,
        `    );`,
        `});`,
        `self.${nameOfTheGlobal} = env;`
    ].join("\n");

    try {
        fs.writeFileSync(pathJoin(distDirPath, "swEnv.js"), Buffer.from(swEnv, "utf8"));
    } catch (error) {
        assert(is<Error>(error));

        // Test if permission error

        if (!error.message.includes("permission denied")) {
            throw error;
        }

        console.log(
            "Not enough permissions to update the swEnv.js file. It's not an issue if you don't explicitly use it"
        );
    }
}
